version: "2.4"

services:
  nginx:
    depends_on:
      - mattermost
    container_name: nginx_mattermost
    image: nginx:${NGINX_IMAGE_TAG}
    restart: ${RESTART_POLICY}
    security_opt:
      - no-new-privileges:true
    pids_limit: 100
    read_only: true
    tmpfs:
      - /var/run
      - /var/cache
    volumes:
      - ${NGINX_CONFIG_PATH}:/etc/nginx/conf.d:rw
      - ${NGINX_DHPARAMS_FILE}:/dhparams4096.pem
      - ${NGINX_LOG_PATH}:/var/log/nginx
    environment:
      - TZ
    ports:
      - ${HTTP_PORT}:8282
  mattermost:
    ports:
      - ${CALLS_PORT}:${CALLS_PORT}/udp
      - ${CALLS_PORT}:${CALLS_PORT}/tcp

# This network name is being used for Let's Encrypt certificate renewal
networks:
  default:
    name: mattermost
